In [1]:
# import the needed libraries/packages
# os means operating_system
# import os
# pandas
import pandas as pd
import numpy as np
import csv

In [2]:
# read data source and store in a variable named "df"
df = pd.read_json('data.json')
len(df)

51821

In [3]:
# check first 5 data, and as you can see in the result below, a dataframe is really just  a table
df.head()

,id,operatingUnit,spatialCoverage,region,province,commodityGroup,commodity,valueChainSegment,function,subprogram,...,investment_6,investmentTotal,municipalities_1,municipalities_2,municipalities_3,municipalities_4,municipalities_5,municipalities_6,fundSource,remarks
0,1,RFO 11,Regional,Region 11,Davao del Norte,Livestock,Chicken (Native),Functional Service,"Extension Support, Education and Training Serv...",,...,0.0,200000.0,0,0,1,0,0,0,DA,Tagum
1,2,RFO 11,Regional,Region 11,Davao del Norte,Livestock,Carabao,Functional Service,"Extension Support, Education and Training Serv...",,...,0.0,200000.0,0,0,1,0,0,0,DA,Tagum
2,3,RFO 11,Regional,Region 11,Davao City,High Value Crops,Vegetables,Production,Production Support Services,,...,0.0,400000.0,0,0,1,0,0,0,"DA, LGU",Davao City
3,4,RFO 11,Regional,Region 11,Davao del Norte,Livestock,Chicken (Native),Production,Production Support Services,,...,0.0,500000.0,0,0,1,0,0,0,DA,Tagum
4,5,RFO 11,Regional,Region 11,Davao Oriental,Rice,Rice,Input Supply,Production Support Services,,...,0.0,500000.0,0,0,1,0,0,0,DA,Boston

In [4]:
# we rename the columns here although this is quite unnecessary since the column names are already decent
df.columns = ['id','operating_unit','spatial_coverage','region','province','commodity_group','commodity','value_chain_segment','program','subprogram','intervention_type','intervention','intervention_others','unit','intervention_details','multi_year','target_1','target_2','target_3','target_4','target_5','target_6','investment_1','investment_2','investment_3','investment_4','investment_5','investment_6','investment_total','municipalities_1','municipalities_2','municipalities_3','municipalities_4','municipalities_5','municipalities_6','fund_source','remarks']
# an alternative syntax is to define the columns using a dict type data
# df.rename(columns={
#    'id': 'index',
#    'operatingUnit': 'operating_unit'
#    ...rest of code
# }, inplace=True)

In [5]:
# the codes below replace blank values with na. This is necessary to assign "na" or "not applicable" as another category, 
# otherwise they will be skipped
# the "inplace=True" option here means to modify the original dataframe
df['province'].replace('','na', inplace=True)
df['unit'].replace('','na', inplace=True)
df['subprogram'].replace('','na', inplace=True)

In [6]:
# recode data into category
# first, we change its data type with "astype('category')", then use ".cat.codes" to implement the actual change
df['operating_unit'] = df['operating_unit'].astype('category')
df['operating_unit_id'] = df['operating_unit'].cat.codes
df['spatial_coverage'] = df['spatial_coverage'].astype('category')
df['spatial_coverage_id'] = df['spatial_coverage'].cat.codes
df['region'] = df['region'].astype('category')
df['region_id'] = df['region'].cat.codes
df['province'] = df['province'].astype('category')
df['province_id'] = df['province'].cat.codes
df['commodity_group'] = df['commodity_group'].astype('category')
df['commodity_group_id'] = df['commodity_group'].cat.codes
df['commodity'] = df['commodity'].astype('category')
df['commodity_id'] = df['commodity'].cat.codes
df['value_chain_segment'] = df['value_chain_segment'].astype('category')
df['value_chain_segment_id'] = df['value_chain_segment'].cat.codes
df['program'] = df['program'].astype('category')
df['program_id'] = df['program'].cat.codes
df['subprogram'] = df['subprogram'].astype('category')
df['subprogram_id'] = df['subprogram'].cat.codes
df['unit'] = df['unit'].astype('category')
df['unit_id'] = df['unit'].cat.codes
df['multi_year'] = df['multi_year'].astype('category')
df['multi_year'] = df['multi_year'].cat.codes

# get sample data to show the changes
df.sample(5)

,id,operating_unit,spatial_coverage,region,province,commodity_group,commodity,value_chain_segment,program,subprogram,...,operating_unit_id,spatial_coverage_id,region_id,province_id,commodity_group_id,commodity_id,value_chain_segment_id,program_id,subprogram_id,unit_id
48389,48390,RFO 5,Regional,Region 5,Sorsogon,Organic,Rice,Postharvest and Processing,"Agricultural Machinery, Equipment, and Facilit...",Others,...,28,2,13,94,6,284,6,0,31,184
28436,28437,RFO 11,Regional,Region 11,Davao Occidental,Fisheries,Eel,Functional Service,Research and Development,Research and Development,...,21,2,7,30,2,121,0,12,36,184
8223,8224,RFO 9,Regional,Region 9,Zamboanga del Sur,High Value Crops,Rubber,Input Supply,Production Support Services,Production Support Services,...,32,2,17,107,4,301,1,11,34,182
15950,15951,RFO 7,Regional,Region 7,Bohol,Organic,Rice,Production,"Agricultural Machinery, Equipment, and Facilit...","Agricultural Machinery, Equipment, and Facilit...",...,30,2,15,14,6,284,7,0,0,182
23376,23377,RFO 9,Regional,Region 9,Zamboanga Sibugay,High Value Crops,Rubber,Input Supply,Production Support Services,Production Support Services,...,32,2,17,105,4,301,1,11,34,182

In [7]:
# I noticed that some data seem to be missing in the investment_total and I am guessing it's because of adding some invalid raw data
# So I changed the investment_total into sum of the investment_n columns
df['target_total'] = (df['target_1'] + df['target_2'] + df['target_3'] + df['target_4'] + df['target_5'] + df['target_6'])
df['investment_total'] = (df['investment_1'] + df['investment_2'] + df['investment_3'] + df['investment_4'] + df['investment_5'] + df['investment_6'])
df.sample(5)

,id,operating_unit,spatial_coverage,region,province,commodity_group,commodity,value_chain_segment,program,subprogram,...,spatial_coverage_id,region_id,province_id,commodity_group_id,commodity_id,value_chain_segment_id,program_id,subprogram_id,unit_id,target_total
737,738,RFO 2,Regional,Region 2,Cagayan,Fisheries,Shrimps,Market,Market Development Services,Market Development Services,...,2,9,18,2,324,2,8,23,184,25.0
2666,2667,RFO CAR,Regional,CAR,Abra,High Value Crops,Banana,Postharvest and Processing,"Agricultural Machinery, Equipment, and Facilit...","Agricultural Machinery, Equipment, and Facilit...",...,2,1,0,4,25,6,0,0,184,4000.0
9791,9792,RFO 8,Regional,Region 8,Samar,Rice,Rice,Production,Irrigation Network Services,Irrigation Network Services,...,2,16,90,7,284,7,7,20,184,27.0
22337,22338,RFO 6,Regional,Region 6,Aklan,Livestock,Goat,Functional Service,"Extension Support, Education and Training Serv...","Extension Support, Education and Training Serv...",...,2,14,3,5,149,0,5,13,182,2000.0
31375,31376,RFO 11,Regional,Region 11,Compostela Valley,Fisheries,Aquaculture,Functional Service,"Extension Support, Education and Training Serv...","Extension Support, Education and Training Serv...",...,2,7,27,2,14,0,5,13,184,1100.0

In [8]:
# check datatypes, this is not necessary but we was want to see that.
df.dtypes

id                           int64
operating_unit            category
spatial_coverage          category
region                    category
province                  category
commodity_group           category
commodity                 category
value_chain_segment       category
program                   category
subprogram                category
intervention_type           object
intervention                object
intervention_others         object
unit                      category
intervention_details        object
multi_year                    int8
target_1                   float64
target_2                   float64
target_3                   float64
target_4                   float64
target_5                   float64
target_6                   float64
investment_1               float64
investment_2               float64
investment_3               float64
investment_4               float64
investment_5               float64
investment_6               float64
investment_total           float64
municipalities_1             int64
municipalities_2             int64
municipalities_3             int64
municipalities_4             int64
municipalities_5             int64
municipalities_6             int64
fund_source                 object
remarks                     object
operating_unit_id             int8
spatial_coverage_id           int8
region_id                     int8
province_id                   int8
commodity_group_id            int8
commodity_id                 int16
value_chain_segment_id        int8
program_id                    int8
subprogram_id                 int8
unit_id                      int16
target_total               float64
dtype: object

In [9]:
# this is a reusable function which I used to export the categories into files
# this function takes on the following arguments: csv_file (name of csv file that will be exported), 
# csv_columns (name of the columns) and dict_data (the data that will be exported)
def writeToCsv(csv_file,csv_columns,dict_data):
    # convert dict to list
    data_list = dict_data.items()
    try:
        with open(csv_file, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile, dialect='excel', quoting=csv.QUOTE_NONNUMERIC)
            writer.writerow(csv_columns)
            for data in data_list:
                writer.writerow(data)
    except IOError as err:
        errno, strerror = err.args
        print("I/O error({0}): {1}".format(errno, strerror))    
    return

In [10]:
# we define the name of columns here
csv_columns = ['id','name']

In [11]:
# define the column by enumerating the categories and casting it to dict data type
operating_unit = dict(enumerate(df['operating_unit'].cat.categories))
# call the writeToCsv column
writeToCsv('operating_unit.csv',csv_columns,operating_unit)

In [12]:
program = dict(enumerate(df['program'].cat.categories))
writeToCsv('program.csv',csv_columns,program)

In [13]:
subprogram = dict(enumerate(df['subprogram'].cat.categories))
writeToCsv('subprogram.csv',csv_columns,subprogram)

In [14]:
unit = dict(enumerate(df['unit'].cat.categories))
writeToCsv('unit.csv',csv_columns,unit)

In [15]:
value_chain_segment = dict(enumerate(df['value_chain_segment'].cat.categories))
writeToCsv('value_chain_segment.csv',csv_columns,value_chain_segment)

In [16]:
commodity = dict(enumerate(df['commodity'].cat.categories))
writeToCsv('commodity.csv',csv_columns,commodity)

In [17]:
commodity_group = dict(enumerate(df['commodity_group'].cat.categories))
writeToCsv('commodity_group.csv',csv_columns,commodity_group)

In [18]:
province = dict(enumerate(df['province'].cat.categories))
writeToCsv('province.csv',csv_columns,province)

In [19]:
region = dict(enumerate(df['region'].cat.categories))
writeToCsv('region.csv',csv_columns,region)

In [20]:
spatial_coverage = dict(enumerate(df['spatial_coverage'].cat.categories))
writeToCsv('spatial_coverage.csv',csv_columns,spatial_coverage)

In [21]:
# I listed down the columns that have been recoded
columns_to_remove = ['operating_unit','spatial_coverage','region','province','commodity_group','commodity','value_chain_segment','program','subprogram','unit']
# then call drop these columns, axis refers to columns
df.drop(columns_to_remove, axis=1, inplace=True)

In [22]:
# finally export the interventions csv file
# export to csv
df.to_csv('interventions.csv', sep=',', float_format='%.2f', encoding='utf-8', index=False, na_rep='')