In [1]:
import os
import pandas as pd
import numpy as np
import csv

In [2]:
# read data source
df = pd.read_json('data.json')
len(df)

51821

In [3]:
# check first 5 data
df.head()

,id,operatingUnit,spatialCoverage,region,province,commodityGroup,commodity,valueChainSegment,function,subprogram,...,investment_6,investmentTotal,municipalities_1,municipalities_2,municipalities_3,municipalities_4,municipalities_5,municipalities_6,fundSource,remarks
0,1,RFO 11,Regional,Region 11,Davao del Norte,Livestock,Chicken (Native),Functional Service,"Extension Support, Education and Training Serv...",,...,0.0,200000.0,0,0,1,0,0,0,DA,Tagum
1,2,RFO 11,Regional,Region 11,Davao del Norte,Livestock,Carabao,Functional Service,"Extension Support, Education and Training Serv...",,...,0.0,200000.0,0,0,1,0,0,0,DA,Tagum
2,3,RFO 11,Regional,Region 11,Davao City,High Value Crops,Vegetables,Production,Production Support Services,,...,0.0,400000.0,0,0,1,0,0,0,"DA, LGU",Davao City
3,4,RFO 11,Regional,Region 11,Davao del Norte,Livestock,Chicken (Native),Production,Production Support Services,,...,0.0,500000.0,0,0,1,0,0,0,DA,Tagum
4,5,RFO 11,Regional,Region 11,Davao Oriental,Rice,Rice,Input Supply,Production Support Services,,...,0.0,500000.0,0,0,1,0,0,0,DA,Boston

In [4]:
# rename columns
df.columns = ['id','operating_unit','spatial_coverage','region','province','commodity_group','commodity','value_chain_segment','program','subprogram','intervention_type','intervention','intervention_others','unit','intervention_details','multi_year','target_1','target_2','target_3','target_4','target_5','target_6','investment_1','investment_2','investment_3','investment_4','investment_5','investment_6','investment_total','municipalities_1','municipalities_2','municipalities_3','municipalities_4','municipalities_5','municipalities_6','fund_source','remarks']

In [5]:
df['province'].replace('','na', inplace=True)
df['unit'].replace('','na', inplace=True)
df['subprogram'].replace('','na', inplace=True)

In [6]:
# recode data
df['operating_unit'] = df['operating_unit'].astype('category')
df['operating_unit_id'] = df['operating_unit'].cat.codes
df['spatial_coverage'] = df['spatial_coverage'].astype('category')
df['spatial_coverage_id'] = df['spatial_coverage'].cat.codes
df['region'] = df['region'].astype('category')
df['region_id'] = df['region'].cat.codes
df['province'] = df['province'].astype('category')
df['province_id'] = df['province'].cat.codes
df['commodity_group'] = df['commodity_group'].astype('category')
df['commodity_group_id'] = df['commodity_group'].cat.codes
df['commodity'] = df['commodity'].astype('category')
df['commodity_id'] = df['commodity'].cat.codes
df['value_chain_segment'] = df['value_chain_segment'].astype('category')
df['value_chain_segment_id'] = df['value_chain_segment'].cat.codes
df['program'] = df['program'].astype('category')
df['program_id'] = df['program'].cat.codes
df['subprogram'] = df['subprogram'].astype('category')
df['subprogram_id'] = df['subprogram'].cat.codes
df['unit'] = df['unit'].astype('category')
df['unit_id'] = df['unit'].cat.codes
df['multi_year'] = df['multi_year'].astype('category')
df['multi_year'] = df['multi_year'].cat.codes

# get sample data
df.sample(5)

,id,operating_unit,spatial_coverage,region,province,commodity_group,commodity,value_chain_segment,program,subprogram,...,operating_unit_id,spatial_coverage_id,region_id,province_id,commodity_group_id,commodity_id,value_chain_segment_id,program_id,subprogram_id,unit_id
34507,34508,RFO 13,Regional,CARAGA,Regionwide (CARAGA),Corn,Cassava,Functional Service,"Extension Support, Education and Training Serv...","Extension Support, Education and Training Serv...",...,23,2,2,87,1,64,0,5,13,184
39691,39692,RFO 4A,Regional,Region 4A,Rizal,High Value Crops,Cashew \n,Production,"Agricultural Machinery, Equipment, and Facilit...","Agricultural Machinery, Equipment, and Facilit...",...,26,2,11,88,4,63,7,0,0,184
42725,42726,RFO 13,Regional,CARAGA,Dinagat Islands,Fisheries,Shellfish,Functional Service,"Extension Support, Education and Training Serv...","Extension Support, Education and Training Serv...",...,23,2,2,34,2,322,0,5,13,184
32697,32698,RFO 1,Regional,Region 1,Ilocos Norte,High Value Crops,Mango,Market,Market Development Services,Market Development Services,...,19,2,5,40,4,216,2,8,23,184
22567,22568,RFO 11,Regional,Region 11,Davao City,High Value Crops,Coffee,Functional Service,"Extension Support, Education and Training Serv...","Extension Support, Education and Training Serv...",...,21,2,7,29,4,86,0,5,13,184

In [7]:
df.dtypes

id                           int64
operating_unit            category
spatial_coverage          category
region                    category
province                  category
commodity_group           category
commodity                 category
value_chain_segment       category
program                   category
subprogram                category
intervention_type           object
intervention                object
intervention_others         object
unit                      category
intervention_details        object
multi_year                    int8
target_1                   float64
target_2                   float64
target_3                   float64
target_4                   float64
target_5                   float64
target_6                   float64
investment_1               float64
investment_2               float64
investment_3               float64
investment_4               float64
investment_5               float64
investment_6               float64
investment_total           float64
municipalities_1             int64
municipalities_2             int64
municipalities_3             int64
municipalities_4             int64
municipalities_5             int64
municipalities_6             int64
fund_source                 object
remarks                     object
operating_unit_id             int8
spatial_coverage_id           int8
region_id                     int8
province_id                   int8
commodity_group_id            int8
commodity_id                 int16
value_chain_segment_id        int8
program_id                    int8
subprogram_id                 int8
unit_id                      int16
dtype: object

In [8]:
def writeToCsv(csv_file,csv_columns,dict_data):
    # convert dict to list
    data_list = dict_data.items()
    try:
        with open(csv_file, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile, dialect='excel', quoting=csv.QUOTE_NONNUMERIC)
            writer.writerow(csv_columns)
            for data in data_list:
                writer.writerow(data)
    except IOError as err:
        errno, strerror = err.args
        print("I/O error({0}): {1}".format(errno, strerror))    
    return

In [9]:
csv_columns = ['id','name']

In [10]:
operating_unit = dict(enumerate(df['operating_unit'].cat.categories))
writeToCsv('operating_unit.csv',csv_columns,operating_unit)

In [11]:
program = dict(enumerate(df['program'].cat.categories))
writeToCsv('program.csv',csv_columns,program)

In [12]:
subprogram = dict(enumerate(df['subprogram'].cat.categories))
print(subprogram)
writeToCsv('subprogram.csv',csv_columns,subprogram)

{0: 'Agricultural Machinery, Equipment, and Facilities Support Services', 1: 'Agriculture and Fishery Policy Services', 2: 'Agriculture and Fishery Regulatory Support', 3: 'Block Farm Program', 4: 'Bridge Construction and Repair', 5: 'Coconut Industry Development Program', 6: 'Credit Facilitation Services', 7: 'Credit Facilitation Services\n', 8: 'Credit Support Services', 9: 'Crop Insurance Program', 10: 'Cross-Cutting', 11: 'Dairy Industry Development Program', 12: 'Development of organizational policies, plans and procedures', 13: 'Extension Support, Education and Training Services', 14: 'Farm-to-Mill Roads', 15: 'Farm-to-market Road Network Services', 16: 'Fisheries Infrastructure Development Program', 17: 'Formulation, monitoring and evaluation of agricultural and fishery policies, plans and programs', 18: 'Hatcheries maintained', 19: 'Information Support Services', 20: 'Irrigation Network Services', 21: 'Irrigation Systems Development Program', 22: 'Irrigation Systems Restoration/Repair/Rehabilitation Program', 23: 'Market Development Services', 24: 'Natural/Ecological Infrastructure', 25: 'Non-DA Programs', 26: 'Non-DA programs', 27: 'Operation and Maintenance of Integrated Laboratories', 28: 'Operations  for Function and Operations and maintenance of integrated laboratories for Sub-Program', 29: 'Operations and maintenance of integrated laboratories', 30: 'Other Infrastructure and Facilities', 31: 'Others', 32: 'Postharvest Equipment and Facilities', 33: 'Postharvest Facilities established', 34: 'Production Support Services', 35: 'Research & Development', 36: 'Research and Development', 37: 'Research and Development Program', 38: 'SWIP', 39: 'Scholarship Program', 40: 'Socialized Credit Program', 41: 'Support to Credit Operations', 42: 'Support to Operations', 43: 'na'}

In [13]:
unit = dict(enumerate(df['unit'].cat.categories))
print(unit)
writeToCsv('unit.csv',csv_columns,unit)

{0: '4WD Tractor Distributed (number)', 1: 'Area (has)', 2: 'Area (has.)', 3: 'Area planted', 4: 'Bag', 5: 'Combine Harvester distributed (number)', 6: 'Farmers Insured (No.)', 7: 'Goat distributed', 8: 'Groups assisted to access credit', 9: 'HT distributed', 10: 'Head', 11: 'Hectares', 12: 'Individuals assisted (No.)', 13: 'Kilogram', 14: 'Kilometer', 15: 'Litre', 16: 'Metric-ton', 17: 'No of Corn Dehuskers distributed', 18: 'No of Multi-purpose drying pavement constructed', 19: 'No of bags', 20: 'No of trainings conducted', 21: 'No of units distributed', 22: 'No, of activities participated', 23: 'No.', 24: 'No. of 4 WD tractor distributed', 25: 'No. of 4-Wheel Drive Tractor', 26: 'No. of 4-row corn planter distributed', 27: 'No. of Cluster areas (Hybrid)', 28: 'No. of Common Service Facility established', 29: 'No. of FBS conducted', 30: 'No. of FSB conducted', 31: 'No. of Facility established', 32: 'No. of Fertlizer Bags provided', 33: 'No. of Field Day conducted', 34: 'No. of Mango growers associations/ groups strengthened', 35: 'No. of Market Matching conducted', 36: 'No. of Market Matching/linkages conducted', 37: 'No. of Market fora conducted', 38: 'No. of Market forum conducted', 39: 'No. of Nurseries established', 40: 'No. of Nursery Established', 41: 'No. of Orientations Conducted', 42: 'No. of Planting Materials Distributed', 43: 'No. of Planting Materials distributed', 44: 'No. of Rain shelter established', 45: 'No. of SSF established', 46: 'No. of Seed Storage constructed', 47: 'No. of Seminars conducted', 48: 'No. of Spring development constructed', 49: 'No. of Techno Demo established', 50: 'No. of Techno demo established', 51: 'No. of Techno demo establsihed', 52: 'No. of Trade Fairs conducted', 53: 'No. of Two-row Planters distributed', 54: 'No. of activities conducted', 55: 'No. of agri-fair participated', 56: 'No. of asexually propagated planting materials distributed', 57: 'No. of bags', 58: 'No. of benchmarking activities conducted', 59: 'No. of borrowers', 60: 'No. of certification subsidized', 61: 'No. of certified seedlings distributed', 62: 'No. of conducted trainings', 63: 'No. of conferences conducted', 64: 'No. of facilities established', 65: 'No. of facilities installed', 66: 'No. of facility established', 67: 'No. of farms certified', 68: 'No. of farms subsidized', 69: 'No. of fora conducted', 70: 'No. of gabi runners distributed', 71: 'No. of ha. Established', 72: 'No. of hauling vehicles procured', 73: 'No. of hectares provided with bufferstock', 74: 'No. of hermetic cocoons distributed', 75: 'No. of investment fora conducted', 76: 'No. of investment forum conducted', 77: 'No. of kg distributed', 78: 'No. of kgs distributed', 79: 'No. of kgs. distributed', 80: 'No. of learning sites establsihed', 81: 'No. of linkage conducted to other buyers', 82: 'No. of linkages to big processors conducted', 83: 'No. of market expo conducted', 84: 'No. of marketing establishment identified for Masbate Mango conducted', 85: 'No. of mechanical dryer distributed', 86: 'No. of meetings conducted', 87: 'No. of nurseries established', 88: 'No. of nursery established', 89: 'No. of packs distributed', 90: 'No. of pieces', 91: 'No. of pili Service Provider organized', 92: 'No. of pili farmer assocations organized', 93: 'No. of planting materials (cuttings)', 94: 'No. of planting materials distributed', 95: 'No. of planting materials distributed (pcs)', 96: 'No. of planting materials provided', 97: 'No. of processing equipment distributed', 98: 'No. of processing equipment set procured', 99: 'No. of processing facility', 100: 'No. of processing facility established', 101: 'No. of researches conducted', 102: 'No. of sets distributed', 103: 'No. of solar dryer distributed', 104: 'No. of techno demo established', 105: 'No. of technology demo established', 106: 'No. of trade fairs conducted', 107: 'No. of trading post established', 108: 'No. of trainings conducted', 109: 'No. of tranings conducted', 110: 'No. of trials conducted', 111: 'No. of units constructed', 112: 'No. of units distirbuted', 113: 'No. of units distributed', 114: 'No. of units established', 115: 'No. of units installed', 116: 'No. planting materials distributed', 117: 'No. researches conducted', 118: 'No. units distributed', 119: 'No.of seed banking established', 120: 'Number', 121: 'Number of Farmers', 122: 'Number of Hauling Truck Distributed', 123: 'Number of Heads', 124: 'Number of IEC Materials dsitributed', 125: 'Number of STW installed', 126: 'Number of Trainings conducted', 127: 'Number of Two-Row Corn planter distributed', 128: 'Number of Vehicles procured', 129: 'Number of bags of fertilizers distributed', 130: 'Number of clustered organizations', 131: 'Number of demo farm established', 132: 'Number of facilities established', 133: 'Number of researches conducted', 134: 'Number of scion grove established', 135: 'Number of trainings conducted', 136: 'Number of units', 137: 'Number of units distributed', 138: 'Numberof Unit', 139: 'Piece', 140: 'Pieces', 141: 'Transplanter Distributed (number)', 142: 'Unit', 143: 'bag', 144: 'bags', 145: 'barangay', 146: 'batch', 147: 'bottle', 148: 'box', 149: 'bundle', 150: 'can', 151: 'colony', 152: 'copies', 153: 'cuttings', 154: 'day', 155: 'dose', 156: 'doses', 157: 'feet', 158: 'gallon', 159: 'galoon', 160: 'gram', 161: 'group', 162: 'ha', 163: 'hd', 164: 'head', 165: 'hectare', 166: 'hectares', 167: 'hour', 168: 'kg', 169: 'kilogram', 170: 'kilometer', 171: 'kilometers', 172: 'kit', 173: 'km', 174: 'linear meter', 175: 'liter', 176: 'liters', 177: 'lt', 178: 'meter', 179: 'metric ton', 180: 'million pieces', 181: 'module', 182: 'na', 183: 'no. of PISOS distributed', 184: 'number', 185: 'number of bags', 186: 'others', 187: 'pack', 188: 'package', 189: 'packet', 190: 'packs', 191: 'pax', 192: 'pc', 193: 'pcs', 194: 'percent', 195: 'peso', 196: 'piece', 197: 'pieces', 198: 'roll', 199: 'sachet', 200: 'sack', 201: 'set', 202: 'site', 203: 'sites', 204: 'square', 205: 'square foot', 206: 'square meter', 207: 'sucker', 208: 'unit', 209: 'units', 210: 'vial'}

In [14]:
value_chain_segment = dict(enumerate(df['value_chain_segment'].cat.categories))
writeToCsv('value_chain_segment.csv',csv_columns,value_chain_segment)

In [15]:
commodity = dict(enumerate(df['commodity'].cat.categories))
writeToCsv('commodity.csv',csv_columns,commodity)

In [16]:
commodity_group = dict(enumerate(df['commodity_group'].cat.categories))
writeToCsv('commodity_group.csv',csv_columns,commodity_group)

In [17]:
province = dict(enumerate(df['province'].cat.categories))
print(province)
writeToCsv('province.csv',csv_columns,province)

{0: 'Abra', 1: 'Agusan del Norte', 2: 'Agusan del Sur', 3: 'Aklan', 4: 'Albay', 5: 'Antique', 6: 'Apayao', 7: 'Aurora', 8: 'Basilan', 9: 'Bataan', 10: 'Batanes', 11: 'Batangas', 12: 'Benguet', 13: 'Biliran', 14: 'Bohol', 15: 'Bukidnon', 16: 'Bulacan', 17: 'Butuan City', 18: 'Cagayan', 19: 'Cagayan de Oro City', 20: 'Camarines Norte', 21: 'Camarines Sur', 22: 'Camiguin', 23: 'Capiz', 24: 'Catanduanes', 25: 'Cavite', 26: 'Cebu', 27: 'Compostela Valley', 28: 'Cotabato (North Cotabato)', 29: 'Davao City', 30: 'Davao Occidental', 31: 'Davao Oriental', 32: 'Davao del Norte', 33: 'Davao del Sur', 34: 'Dinagat Islands', 35: 'Eastern Samar', 36: 'General Santos City', 37: 'Guimaras', 38: 'Ifugao', 39: 'Iligan City', 40: 'Ilocos Norte', 41: 'Ilocos Sur', 42: 'Iloilo', 43: 'Iloilo City', 44: 'Inter-regional', 45: 'Isabela', 46: 'Kalinga', 47: 'La Union', 48: 'Laguna', 49: 'Lanao del Norte', 50: 'Lanao del Sur', 51: 'Leyte', 52: 'Maguindanao', 53: 'Marinduque', 54: 'Masbate', 55: 'Misamis Occidental', 56: 'Misamis Oriental', 57: 'Mountain Province', 58: 'Nationwide', 59: 'Negros Occidental', 60: 'Negros Oriental', 61: 'Northern Samar', 62: 'Nueva Ecija', 63: 'Nueva Vizcaya', 64: 'Occidental Mindoro', 65: 'Oriental Mindoro', 66: 'Palawan', 67: 'Pampanga', 68: 'Pangasinan', 69: 'Puerto Princesa City', 70: 'Quezon', 71: 'Quirino', 72: 'Regionwide', 73: 'Regionwide (1)', 74: 'Regionwide (10)', 75: 'Regionwide (11)', 76: 'Regionwide (12)', 77: 'Regionwide (2)', 78: 'Regionwide (3)', 79: 'Regionwide (4A)', 80: 'Regionwide (4B)', 81: 'Regionwide (5)', 82: 'Regionwide (6)', 83: 'Regionwide (8)', 84: 'Regionwide (9)', 85: 'Regionwide (ARMM)', 86: 'Regionwide (CAR)', 87: 'Regionwide (CARAGA)', 88: 'Rizal', 89: 'Romblon', 90: 'Samar', 91: 'Santiago City', 92: 'Sarangani', 93: 'Siquijor', 94: 'Sorsogon', 95: 'South Cotabato', 96: 'Southern Leyte', 97: 'Sultan Kudarat', 98: 'Sulu', 99: 'Surigao del Norte', 100: 'Surigao del Sur', 101: 'Tarlac', 102: 'Tawi-Tawi', 103: 'Zambales', 104: 'Zamboanga City', 105: 'Zamboanga Sibugay', 106: 'Zamboanga del Norte', 107: 'Zamboanga del Sur', 108: 'na'}

In [18]:
region = dict(enumerate(df['region'].cat.categories))
writeToCsv('region.csv',csv_columns,region)

In [19]:
spatial_coverage = dict(enumerate(df['spatial_coverage'].cat.categories))
writeToCsv('spatial_coverage.csv',csv_columns,spatial_coverage)

In [20]:
columns_to_remove = ['operating_unit','spatial_coverage','region','province','commodity_group','commodity','value_chain_segment','program','subprogram','unit']
df.drop(columns_to_remove, axis=1, inplace=True)

In [21]:
df.head()

,id,intervention_type,intervention,intervention_others,intervention_details,multi_year,target_1,target_2,target_3,target_4,...,operating_unit_id,spatial_coverage_id,region_id,province_id,commodity_group_id,commodity_id,value_chain_segment_id,program_id,subprogram_id,unit_id
0,1,Others,Stregthen/Conduct of Poultry Production and He...,,No. of training conducted,0,0.0,0.0,1.0,0.0,...,21,2,7,32,5,76,0,5,43,184
1,2,Others,Training on Integrated Farming,,No. of integrated farming conducted,0,0.0,0.0,1.0,0.0,...,21,2,7,32,5,56,0,5,43,184
2,3,Others,Development of multiplier farms to increase th...,,No of multiplier farms developed,0,0.0,0.0,1.0,0.0,...,21,2,7,29,4,369,7,11,43,184
3,4,Others,Dispersal of Native Chicken,,No. of native chicken dispersed,0,0.0,0.0,2500.0,0.0,...,21,2,7,32,5,76,7,11,43,184
4,5,Others,Provision of certified rice seeds,,No of certified rice seeds provided,0,0.0,0.0,333.0,0.0,...,21,2,7,31,7,284,1,11,43,169

In [22]:
# export to csv
df.to_csv('interventions.csv', sep=',', float_format='%.2f', encoding='utf-8', index=False)